apiVersion: apps/v1
kind: Deployment
metadata:
  name: customerinformation-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: addressbook
  template:
    metadata:
      labels:
        app: addressbook
    spec:
      containers:
        - name: addressbook-container
          image: suhailasad/addressbook:1.2
          ports:
            - containerPort: 8080
